### ISSUE TITLE
Man page wrong regarding -f 

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdb_c#9]
If the \-f option is present, then dnsdb_query will read commands from stdin (not from a batch file name).

The man page has synopsis:
```
 [-dfhjv] [-A timestamp] [-B timestamp] [-b bailiwick] [-i ip] [-l limit] [-n name] [-p output_type]
     [-r rdata] [-t type] [batch_filename]
```
The \[batch_filename\] part should be removed.  

The documentation for the \-f command should be changed from ```in a file``` to ```in stdin```.

**Comment by vixie** [comment]
fixed in commit 9ce7c5cf219e81ef59e3b933a06dffacb305c132
